### PR TITLE
build(GitHub Actions): fix syntax error

### PR DESCRIPTION
**Pull request by dnaroma**
This should pass without errors

### CODE REVIEW

**Comment by Build774** [comment]
It seems to [require artifacts to share files between jobs](https://docs.github.com/en/free-pro-team@latest/actions/guides/storing-workflow-data-as-artifacts).
I suggest to merge `prepare_env` and `build`, and use artifacts between `build` and `deploy`.

**Comment by dnaroma** [comment]
> It seems to [require artifacts to share files between jobs](https://docs.github.com/en/free-pro-team@latest/actions/guides/storing-workflow-data-as-artifacts).
> I suggest to merge `prepare_env` and `build`, and use artifacts between `build` and `deploy`.

Yes and I have done like that.

**Comment by Build774** [comment]
Very good. Maybe you have to update Worker's secret too.

**Comment by dnaroma** [comment]
I set wrong secret and have updated the right value. It finally works.

**Comment by Build774** [comment]
I noticed that I didn't configure to delete branch after PR is closed/merged.  
It'd be better to make it before the repository gets bloated.

**Pull request merged**
