### PR TITLE
layout(StampList): more stamp columns

### PR DESCRIPTION
**Pull request by Build774**
Depends on #30.  
Any comments and suggestions are welcome.

Preview:
stamp-1920x1080
stamp-1024x576
stamp-iPad
stamp-Pixel2

### CODE REVIEW

**Comment by iSwanGit** [comment]
The header name is Gacha...??? (i think probably just a missing point)

**Comment by dnaroma** [comment]
> The header name is Gacha...??? (i think probably just a missing point)

That's a bug. Copy and paste mistake xD

**Comment by Build774** [comment]
@iSwanGit  @dnaroma That's fixed in f65d9f0 (Though it's not a good idea to include multiple changes in one PR.)

**Comment by iSwanGit** [comment]
Right. I just only saw screenshot, sorry! 😅

**Comment by dnaroma** [comment]
Thanks for refactoring InfiniteScroll to support more breakpoints! It can help other pages too

**Pull request merged**
