### PR TITLE
 feat(MusicDetail): skip beginning silence

### PR DESCRIPTION
**Pull request by Build774**
I've tested this working on my Chrome on Windows, Firefox on Windows, Chrome on Android but not sure if this works on other environments (especially on old browsers).

### CODE REVIEW

**Review by iSwanGit — APPROVED** [review]

**Review by iSwanGit — APPROVED** [review]

**Comment by iSwanGit** [comment]
Oh sorry
I reviewed only some of commits, but I pressed the review button incorrectly (I thought I can check review per commit)

**Comment by Build774** [comment]
It's okay.
Feel free to comment if there are any suggestions (for translation, algorithm, etc.), questions or anything else.

**Comment by Build774** [comment]
Resolved conflicts.

**Comment by dnaroma** [comment]
Hi,
I'm wondering if the trimming function should start once user has switched to the tabpanel "LONG VERSION"?
Besides, it's better to have a loading indicator since it's doing something that costs time and the switch button is disabled before everything is done.

**Review by dnaroma — APPROVED** [review]

**Comment by Build774** [comment]
> I'm wondering if the trimming function should start once user has switched to the tabpanel "LONG VERSION"?

I did this to reduce load times, but this is not good for pay-as-you-go networks such as mobile devices.
I'll change this behavior.

> it's better to have a loading indicator since it's doing something that costs time and the switch button is disabled before everything is done.

Right. I'll implement it.

> And I think that the warning on the top could also be removed as user can trim the mute part now.

Yes, but MVs still have a mute part.
I'll leave it as is for now.

**Comment by dnaroma** [comment]
>Yes, but MVs still have a mute part.
I'll leave it as is for now.

Yea you're right. So leave it there.

**Comment by iSwanGit** [comment]
> And I think that the warning on the top could also be removed as user can trim the mute part now.

I think it's better to put it inside the LONG VERSION tab, near the trimming function switch rather than removing it.

**Comment by dnaroma** [comment]
> I think it's better to put it inside the LONG VERSION tab, near the trimming function switch rather than removing it.

It's the MV which also have a mute part. Maybe leaving it there is better.

**Comment by Build774** [comment]
Implemented.

**Comment by dnaroma** [comment]
> Implemented.

お疲れ様でした！I'm checking it.

**Pull request merged**
