### PR TITLE
UI improvements

### PR DESCRIPTION
**Pull request by Build774**
## Description

- set lg grid size to 3 on grid view of CardList, MusicList, GachaList and EventList (affects only >= 1280px viewport devices)
- change max width from 960px to 1280px on Home and List pages (affects only > 1248px viewport devices)
- bug fixes about agenda view
  - grid size of agenda view should always be 12 but it was 6 on sm viewport
- minor refactoring of InfiniteScroll

## How Has This Been Tested?

Manually tested.

## Screenshots (if appropriate):

Resolution; 1920x1080 (px)
DPR (Device Pixel Ratio): 2.0

Before | After
:----: | :----:
 | 
 | 
 | 
 | 
 | 
 |

### CODE REVIEW

**Comment by Build774** [comment]
This is a bad PR which is a mixture of fixes and changes, so if you have any feedback, please let me know!

**Comment by dnaroma** [comment]
@NonSpicyBurrito How do you think about this UI change?

**Comment by NonSpicyBurrito** [comment]
From screenshots, it does look quite a bit nicer than before in high res devices. Do double check on smaller breakpoints though.

**Comment by dnaroma** [comment]
> From screenshots, it does look quite a bit nicer than before in high res devices. Do double check on smaller breakpoints though.

@NonSpicyBurrito okay, if you approve this, I will merge

**Review by NonSpicyBurrito — APPROVED** [review]

**Pull request merged**
