### PR TITLE
refactor(InfiniteScroll): revert 6b9d398 and make codes about `gridSize` clearer, revert 

### PR DESCRIPTION
**Pull request by Build774**

### CODE REVIEW

**Comment by dnaroma** [comment]
It failed, I'm debugging

**Comment by Build774** [comment]
Oops, maybe `PR_REPO_NAME` secret is not defined in the project settings? @dnaroma

**Comment by dnaroma** [comment]
I should have set that. Just updated that variable and rerun.
BTW, I'm going to split jobs, then I can rerun from where it fails.

**Comment by Build774** [comment]
That's a good idea. I have spent much time to debug GitHub Actions.

**Comment by dnaroma** [comment]
I think it's the format function which will ignore string from secrets. I will change `pr.yml`.

**Comment by dnaroma** [comment]
@Build774 I've updated script, maybe you can retry?

**Comment by dnaroma** [comment]
I'm sorry I made another mistake.

**Comment by dnaroma** [comment]
I can guess the cause. The secrets are not shared, in PR it needs your secrets being set.

**Comment by Build774** [comment]
Using `pull_request_target` instead of `pull_request` may resolve the problem?  
ref: [GitHub Actions improvements for fork and pull request workflows](https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/)

**Comment by dnaroma** [comment]
> Using `pull_request_target` instead of `pull_request` may resolve the problem?
> ref: [GitHub Actions improvements for fork and pull request workflows](https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/)

Give it a try. You can push a new commit for it in this PR.

**Comment by dnaroma** [comment]
This time, I think it's the GITHUB_TOKEN. The token in this env may only have access to this repo. Let me set a token as secret.

**Comment by dnaroma** [comment]
@Build774 I have that done and updated `pr.yml`. I'm sorry that I made some bad changes to your sample file and caused a huge waste of time. I'm also appreciated that you're debugging this with me. Thanks a lot!

**Comment by Build774** [comment]
Never mind.
It's partly because my initial workflow was inadequate.

**Comment by dnaroma** [comment]
Your PR build is now available at [https://sekai-viewer-pr-prod.dnaroma.workers.dev/pr-36/](https://sekai-viewer-pr-prod.dnaroma.workers.dev/pr-36/)!

**Comment by dnaroma** [comment]
It becomes that I'm commenting xD. Finally it works.

**Comment by Build774** [comment]
Could you take a look at Worker's secret?
Maybe it points to `Sekai-World/sekai-viewer-pr` (not `Sekai-World/sekai-viewer`)

**Comment by dnaroma** [comment]
I made a typo in Worker's env.

**Comment by Build774** [comment]
Confirmed it's working! 谢谢你的努力!
Please check this PR at your convenience.
Thank you for your time!

**Comment by Build774** [comment]
> should I remove the corresponding branch in sekai-viewer-pr after the PR is merged?
I think so. I think it's unlikely to someone want to refer back to the PR preview later.

**Comment by dnaroma** [comment]
> Confirmed it's working! 谢谢你的努力!
> Please check this PR at your convenience.
> Thank you for your time!

お疲れ様でした！Thanks for your time too! Also for this amazing workflow to preview PR!

**Pull request merged**
