### PR TITLE
#504 - update character icons

### PR DESCRIPTION
**Pull request by GreydonDesu**
## Description
Changed the round icons for each character with the icons provided from this message: https://github.com/Sekai-World/sekai-viewer/issues/504#issuecomment-2529927903

## Related Issue
#504 

## Motivation and Context
The PR changes the icons to the new character designs from Project Sekai version 3.0.0. For further information, look into #504 

## How Has This Been Tested?

- [x] Chrome (Desktop)
- [x] Chrome (Mobile)
- [x] Firefox (Desktop)
- [x] Firefox (Mobile)
- [ ] Safari (Desktop, optional)
- [ ] Safari (iPhone, optional)
- [ ] Safari (iPad, optional)

## Screenshots (if appropriate):
image

### CODE REVIEW

**Comment by LazytownSpo666** [comment]
@dnaroma can't approve at this time.

**Comment by GreydonDesu** [comment]
> @dnaroma can't approve at this time.

All good, the PR is not critical anyway. Enjoy new year!

**Comment by dnaroma** [comment]
Checks all green, merged

**Comment by dnaroma** [comment]
Deployment awaits though

**Comment by LazytownSpo666** [comment]
I don't think all of the icons were updated yet. only 90x icons were updated. 128x icons are still on the waitlist.

**Pull request merged**
